### ISSUE TITLE
migrate to python3 

### ISSUE THREAD

**Issue by alexanderpanchenko** [shan18/taxi#3]
using the 2to3 tool

**Comment by shan18** [comment]
Converting the code to Python 3 is changing the results, and the only changes I made to the code was adding () to the print function and adding the list() function in some cases.

I think we should try to implement this at the end because most of the pruning algorithms that need to be included also have their implementations in python 3, so at the end, we can do all the conversions together at once.

**Comment by alexanderpanchenko** [comment]
did you try to convert manually or using the 2to3 tool?

i agree that the priority of this task is less than the priority of any
other task, but certainly adding braces to "print" should not change
anything as well (there is something else going on here)

**Comment by shan18** [comment]
I used the 2to3 tool. Maybe it has to do with the ordering of dictionaries in python 3 that you were telling me about that day.

**Comment by alexanderpanchenko** [comment]
i think that using 2to3 may be a problem. you need to apply very carefully
this tool and understand what it does. i suggest to start from scratch and
try converting files one by one with the tool trying to understand the
differences and accept them only if they are acceptable. otherwise, it may
also make sense just to convert everything manually without the help of any
tool.

**Comment by shan18** [comment]
Yes, doing it manually might be more helpful. Will try that.

**Comment by alexanderpanchenko** [comment]
you can also see what 2to3 really does - you can run it in a file by file
diff mode.
